name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: Vedant-Asati03
          # Fix: Change outputs format to match expected pattern
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
