name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Update README
        run: node update-readme.js

      - name: Configure Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and Push Changes
        run: |
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with latest repository data" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}